### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/pivotal-tracker#1]
Let me know when you're done with the code, tests and readme. I'll do a little code review and register your package on Packagist.

**Comment by nbourguig** [comment]
Hi, I think it is ok for me. Let me know if you notice anything.

Btw, do I need to register the repo with travis and the other services ?

**Comment by nbourguig** [comment]
@freekmurze By any chance, did you have any time to take a look at the code ?

**Comment by freekmurze** [comment]
Sorry, this one slipped my mind, will do a review soon (tonight or tomorrow). Sorry for the wait!

**Comment by freekmurze** [comment]
Done, I only changed some minor things.

The only thing that that you should still take care of is the service provider. There's no code there to set up `PivotalTrackerChannel`.  Could you take care of that?

**Comment by nbourguig** [comment]
Okay thx.

I'll go ahead and just remove the generated service provider file (forgot to do it). There is nothing to setup for this package at this point.

**Comment by freekmurze** [comment]
On first thought a service provider is needed to easily create a new instance of `PivotalTrackerChannel`. As it stand a user must inject a `Client` object manually.

It would be nice if it could be resolved out of the IoC-container like this: app(PivotalTrackerChannel::class)`.

**Comment by nbourguig** [comment]
The client is set as a dependency in the PivotalTrackerChannel::class constructor. So it will be injected by the IoC container if one uses app(PivotalTrackerChannel::class)

**Comment by nbourguig** [comment]
Maybe you have a more specific usage in mind ?

**Comment by freekmurze** [comment]
Oh, yes, you're right,  a service provider isn't needed. 

I need more ☕

**Comment by nbourguig** [comment]
Ha ha, I see ;-)
